baseurl = "http://polyconf.com"
title = "PolyConf 15 - Thank You"
languageCode = "en-us"
copyright = "Copyright (c) 2015, RedVLK Foundation; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Zaiste"

[indexes]
    tag = "tags"
    topic = "topics"

